//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.NotificationApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationUser
    {
        public int Id { get; set; }
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<bool> IsPushSent { get; set; }
    
        public virtual Notification Notification { get; set; }
    }
}
