//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.NotificationApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        public Practice()
        {
            this.Leads = new HashSet<Lead>();
            this.PracticeAddressMappers = new HashSet<PracticeAddressMapper>();
            this.PracticeContacts = new HashSet<PracticeContact>();
            this.PracticePracticeSpecialityMappers = new HashSet<PracticePracticeSpecialityMapper>();
            this.PracticeProviderLocationMappers = new HashSet<PracticeProviderLocationMapper>();
            this.PracticeProviderMappers = new HashSet<PracticeProviderMapper>();
            this.PracticeServiceMappers = new HashSet<PracticeServiceMapper>();
            this.ReportMasters = new HashSet<ReportMaster>();
            this.TaskLogs = new HashSet<TaskLog>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string PracticeName { get; set; }
        public Nullable<int> PracticeTypeId { get; set; }
        public string PracticeSpecialityType { get; set; }
        public Nullable<int> ContactPreferenceId { get; set; }
        public Nullable<int> RepId { get; set; }
        public string ReportDeliveryPreference { get; set; }
        public string ReportDeliveryFax { get; set; }
        public string Email { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> OldId { get; set; }
        public Nullable<int> EntrolledServicesId { get; set; }
    
        public virtual BusinessMaster BusinessMaster { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual LookupPracticeType LookupPracticeType { get; set; }
        public virtual Rep Rep { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PracticeAddressMapper> PracticeAddressMappers { get; set; }
        public virtual ICollection<PracticeContact> PracticeContacts { get; set; }
        public virtual ICollection<PracticePracticeSpecialityMapper> PracticePracticeSpecialityMappers { get; set; }
        public virtual ICollection<PracticeProviderLocationMapper> PracticeProviderLocationMappers { get; set; }
        public virtual ICollection<PracticeProviderMapper> PracticeProviderMappers { get; set; }
        public virtual ICollection<PracticeServiceMapper> PracticeServiceMappers { get; set; }
        public virtual ICollection<ReportMaster> ReportMasters { get; set; }
        public virtual ICollection<TaskLog> TaskLogs { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
