//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.NotificationApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep
    {
        public Rep()
        {
            this.Leads = new HashSet<Lead>();
            this.Practices = new HashSet<Practice>();
            this.ReportMasters = new HashSet<ReportMaster>();
            this.RepServiceMappers = new HashSet<RepServiceMapper>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> RepGroupId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> SignonDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> OldId { get; set; }
    
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Practice> Practices { get; set; }
        public virtual RepGroup RepGroup { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<ReportMaster> ReportMasters { get; set; }
        public virtual ICollection<RepServiceMapper> RepServiceMappers { get; set; }
    }
}
