//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.NotificationApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepGroup
    {
        public RepGroup()
        {
            this.Reps = new HashSet<Rep>();
            this.RepgroupManagerMappers = new HashSet<RepgroupManagerMapper>();
        }
    
        public int Id { get; set; }
        public string RepGroupName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> SalesDirectorId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> OldId { get; set; }
    
        public virtual BusinessMaster BusinessMaster { get; set; }
        public virtual ICollection<Rep> Reps { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<RepgroupManagerMapper> RepgroupManagerMappers { get; set; }
    }
}
