//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.NotificationApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskAttachments = new HashSet<TaskAttachment>();
            this.TaskLogs = new HashSet<TaskLog>();
            this.TaskItemOrders = new HashSet<TaskItemOrder>();
            this.TaskUsers = new HashSet<TaskUser>();
            this.TaskUserAlerts = new HashSet<TaskUserAlert>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> TaskRequestTypeId { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> PriorityTypeId { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual BusinessMaster BusinessMaster { get; set; }
        public virtual LookupTaskType LookupTaskType { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<TaskAttachment> TaskAttachments { get; set; }
        public virtual ICollection<TaskLog> TaskLogs { get; set; }
        public virtual ICollection<TaskItemOrder> TaskItemOrders { get; set; }
        public virtual ICollection<TaskUser> TaskUsers { get; set; }
        public virtual ICollection<TaskUserAlert> TaskUserAlerts { get; set; }
    }
}
