//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CacheKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CacheKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBP.Business.Resource.CacheKeys", typeof(CacheKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prdegrees.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ldsources.
        /// </summary>
        public static string LeadSources {
            get {
                return ResourceManager.GetString("LeadSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pctlist.
        /// </summary>
        public static string PracticeList {
            get {
                return ResourceManager.GetString("PracticeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specialities.
        /// </summary>
        public static string PracticeSpecialities {
            get {
                return ResourceManager.GetString("PracticeSpecialities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcttypes.
        /// </summary>
        public static string PracticeTypes {
            get {
                return ResourceManager.GetString("PracticeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prlist.
        /// </summary>
        public static string ProviderList {
            get {
                return ResourceManager.GetString("ProviderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to states.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to tsktype.
        /// </summary>
        public static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
    }
}
