//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBP.Business.Resource.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created an account.
        /// </summary>
        internal static string AccountManagerNotification {
            get {
                return ResourceManager.GetString("AccountManagerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated an account.
        /// </summary>
        internal static string AccountManagerUpdateNotification {
            get {
                return ResourceManager.GetString("AccountManagerUpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created an account for you.
        /// </summary>
        internal static string AccountRepNotification {
            get {
                return ResourceManager.GetString("AccountRepNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  updated your account.
        /// </summary>
        internal static string AccountRepUpdateNotification {
            get {
                return ResourceManager.GetString("AccountRepUpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created a lead.
        /// </summary>
        internal static string LeadManagerNotification {
            get {
                return ResourceManager.GetString("LeadManagerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated a lead.
        /// </summary>
        internal static string LeadManagerUpdateNotification {
            get {
                return ResourceManager.GetString("LeadManagerUpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created a lead for you.
        /// </summary>
        internal static string LeadRepNotification {
            get {
                return ResourceManager.GetString("LeadRepNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  updated your lead.
        /// </summary>
        internal static string LeadRepUpdateNotification {
            get {
                return ResourceManager.GetString("LeadRepUpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new task note added : {1}.
        /// </summary>
        internal static string TaskNoteNotification {
            get {
                return ResourceManager.GetString("TaskNoteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated the task status for: {1}.
        /// </summary>
        internal static string TaskStatusUpdateUserNotification {
            get {
                return ResourceManager.GetString("TaskStatusUpdateUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated task : {1}.
        /// </summary>
        internal static string TaskUpdateUserNotification {
            get {
                return ResourceManager.GetString("TaskUpdateUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created task : {1}.
        /// </summary>
        internal static string TaskUserNotification {
            get {
                return ResourceManager.GetString("TaskUserNotification", resourceCulture);
            }
        }
    }
}
