//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.New
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Phones = new HashSet<Phone>();
            this.PracticeAddressMappers = new HashSet<PracticeAddressMapper>();
            this.PracticeContacts = new HashSet<PracticeContact>();
            this.PracticeProviderLocationMappers = new HashSet<PracticeProviderLocationMapper>();
        }
    
        public int Id { get; set; }
        public int AddressTypeId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string City { get; set; }
        public int StateId { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> IsSecondery { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> OldId { get; set; }
    
        public virtual LookupState LookupState { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<PracticeAddressMapper> PracticeAddressMappers { get; set; }
        public virtual ICollection<PracticeContact> PracticeContacts { get; set; }
        public virtual ICollection<PracticeProviderLocationMapper> PracticeProviderLocationMappers { get; set; }
    }
}
