//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.New
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMStagingEntities : DbContext
    {
        public CRMStagingEntities()
            : base("name=CRMStagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentPrivilege> DepartmentPrivileges { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<LookupCountry> LookupCountries { get; set; }
        public virtual DbSet<LookupDegree> LookupDegrees { get; set; }
        public virtual DbSet<LookupDocumentType> LookupDocumentTypes { get; set; }
        public virtual DbSet<LookupLeadSource> LookupLeadSources { get; set; }
        public virtual DbSet<LookupMarketingCategory> LookupMarketingCategories { get; set; }
        public virtual DbSet<LookupPracticeSpecialityType> LookupPracticeSpecialityTypes { get; set; }
        public virtual DbSet<LookupPracticeType> LookupPracticeTypes { get; set; }
        public virtual DbSet<LookupState> LookupStates { get; set; }
        public virtual DbSet<LookupTaskType> LookupTaskTypes { get; set; }
        public virtual DbSet<MarketingAttachment> MarketingAttachments { get; set; }
        public virtual DbSet<MarketingDocument> MarketingDocuments { get; set; }
        public virtual DbSet<ModulesMaster> ModulesMasters { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationUser> NotificationUsers { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Practice> Practices { get; set; }
        public virtual DbSet<PracticeAddressMapper> PracticeAddressMappers { get; set; }
        public virtual DbSet<PracticeContact> PracticeContacts { get; set; }
        public virtual DbSet<PracticePracticeSpecialityMapper> PracticePracticeSpecialityMappers { get; set; }
        public virtual DbSet<PracticeProviderLocationMapper> PracticeProviderLocationMappers { get; set; }
        public virtual DbSet<PracticeProviderMapper> PracticeProviderMappers { get; set; }
        public virtual DbSet<PracticeServiceMapper> PracticeServiceMappers { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<RepGroup> RepGroups { get; set; }
        public virtual DbSet<ReportColumn> ReportColumns { get; set; }
        public virtual DbSet<RepServiceMapper> RepServiceMappers { get; set; }
        public virtual DbSet<RolePrivilege> RolePrivileges { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SalesDepartmentPrivilege> SalesDepartmentPrivileges { get; set; }
        public virtual DbSet<SalesRolePrivilege> SalesRolePrivileges { get; set; }
        public virtual DbSet<SalesUserPrivilege> SalesUserPrivileges { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskAttachment> TaskAttachments { get; set; }
        public virtual DbSet<TaskItemOrder> TaskItemOrders { get; set; }
        public virtual DbSet<TaskItem> TaskItems { get; set; }
        public virtual DbSet<TaskLog> TaskLogs { get; set; }
        public virtual DbSet<TaskUser> TaskUsers { get; set; }
        public virtual DbSet<TaskUserAlert> TaskUserAlerts { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserDepartment> UserDepartments { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserPrivilege> UserPrivileges { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Rep> Reps { get; set; }
        public virtual DbSet<UserColumnVisibility> UserColumnVisibilities { get; set; }
        public virtual DbSet<ReportMaster> ReportMasters { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<ReportColumnValue> ReportColumnValues { get; set; }
        public virtual DbSet<BusinessMaster> BusinessMasters { get; set; }
        public virtual DbSet<LookupEnrolledService> LookupEnrolledServices { get; set; }
        public virtual DbSet<TempProviderMigrationData> TempProviderMigrationDatas { get; set; }
    }
}
