//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.New
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationUsers = new HashSet<NotificationUser>();
        }
    
        public int Id { get; set; }
        public string Message { get; set; }
        public int TargetId { get; set; }
        public int TargetType { get; set; }
        public int NotificationType { get; set; }
        public string CreatedUserName { get; set; }
        public string ProfilePicUrl { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<NotificationUser> NotificationUsers { get; set; }
    }
}
