//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.New
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportColumn
    {
        public ReportColumn()
        {
            this.SalesDepartmentPrivileges = new HashSet<SalesDepartmentPrivilege>();
            this.SalesRolePrivileges = new HashSet<SalesRolePrivilege>();
            this.SalesUserPrivileges = new HashSet<SalesUserPrivilege>();
            this.ReportColumnValues = new HashSet<ReportColumnValue>();
        }
    
        public int Id { get; set; }
        public int BusinessId { get; set; }
        public int ServiceId { get; set; }
        public string ColumnName { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> DisplayInFilter { get; set; }
        public Nullable<bool> ShowInGrid { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<SalesDepartmentPrivilege> SalesDepartmentPrivileges { get; set; }
        public virtual ICollection<SalesRolePrivilege> SalesRolePrivileges { get; set; }
        public virtual ICollection<SalesUserPrivilege> SalesUserPrivileges { get; set; }
        public virtual ICollection<ReportColumnValue> ReportColumnValues { get; set; }
        public virtual BusinessMaster BusinessMaster { get; set; }
        public virtual LookupEnrolledService LookupEnrolledService { get; set; }
    }
}
