//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.New
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempProviderMigrationData
    {
        public int Id { get; set; }
        public Nullable<int> NewId { get; set; }
        public Nullable<int> OldId { get; set; }
        public string NPI { get; set; }
    }
}
