//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountServices = new HashSet<AccountService>();
        }
    
        public int AccountId { get; set; }
        public int LeadId { get; set; }
        public Nullable<System.DateTime> EnrollDate { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public string Notes { get; set; }
        public string AcctExec { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<AccountService> AccountServices { get; set; }
    }
}
