//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Phones = new HashSet<Phone>();
            this.PracticeContacts = new HashSet<PracticeContact>();
            this.PracticeProviderLocations = new HashSet<PracticeProviderLocation>();
        }
    
        public int AddressId { get; set; }
        public int AddressTypeId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string City { get; set; }
        public int State { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> IsSecondery { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> AddressIdentifier { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual State State1 { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<PracticeContact> PracticeContacts { get; set; }
        public virtual ICollection<PracticeProviderLocation> PracticeProviderLocations { get; set; }
    }
}
