//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert_Lead
    {
        public int AlertId { get; set; }
        public int LeadId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
