//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int ContactId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string HomePhone { get; set; }
        public string OtherPhone { get; set; }
        public string Mobile { get; set; }
        public string Website { get; set; }
        public string LinkedIn { get; set; }
        public string Facebook { get; set; }
        public string Skype { get; set; }
        public string Fax { get; set; }
        public string SecoundryEmail { get; set; }
        public string AssistantPhone { get; set; }
        public string AssistantEmail { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
