//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Doctype { get; set; }
        public string LocationUrl { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Trash { get; set; }
        public Nullable<System.DateTime> IsDeleted { get; set; }
        public string RepGroupId { get; set; }
        public Nullable<int> AccessId { get; set; }
    }
}
