//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpRequest
    {
        public int HRId { get; set; }
        public string HelpId { get; set; }
        public int HelpTypeId { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public int Priority { get; set; }
        public string TargetDate { get; set; }
        public string DateClose { get; set; }
        public string RequestedBy { get; set; }
        public int AssignedTo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> AccountId { get; set; }
        public int Status { get; set; }
        public string Alert { get; set; }
        public string AlertDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
