//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadContact
    {
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public Nullable<int> Degree { get; set; }
        public string Department { get; set; }
        public string ReportsTo { get; set; }
        public string Assistant { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Description { get; set; }
        public string HomeAdders { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
