//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            this.Note_Lead = new HashSet<Note_Lead>();
        }
    
        public int NotesId { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<int> ScriptId { get; set; }
        public Nullable<int> HelpRequestId { get; set; }
        public Nullable<int> NotesTypeId { get; set; }
        public string NotesDescription { get; set; }
        public Nullable<System.Guid> NotesIdentifier { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<Note_Lead> Note_Lead { get; set; }
        public virtual NoteType NoteType { get; set; }
    }
}
