//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPgxreportMap
    {
        public string PatientID { get; set; }
        public string ScriptID { get; set; }
        public string ProviderID { get; set; }
        public string Reporttype { get; set; }
        public Nullable<int> PatientIdFix { get; set; }
        public int NewTempId { get; set; }
    }
}
