//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        public Practice()
        {
            this.PracticeContacts = new HashSet<PracticeContact>();
        }
    
        public int PraticeId { get; set; }
        public string PracticeName { get; set; }
        public int PracticeType { get; set; }
        public Nullable<int> PracticeSpecialityType { get; set; }
        public Nullable<int> EntrolledServicesId { get; set; }
        public string PrefMethodofContact { get; set; }
        public Nullable<int> RepNameId { get; set; }
        public Nullable<int> RepGroupId { get; set; }
        public string RprtDeliveryPreference { get; set; }
        public string PracEmail { get; set; }
        public string PracFax { get; set; }
        public System.DateTime CreateOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Faxno { get; set; }
        public string LastActivityDate { get; set; }
    
        public virtual ICollection<PracticeContact> PracticeContacts { get; set; }
    }
}
