//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_serviceId
    {
        public Nullable<int> LeadServiceID { get; set; }
        public Nullable<int> EnrolledSercvicedId { get; set; }
        public Nullable<int> PracticeID { get; set; }
        public int NewTempId { get; set; }
    }
}
