//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeContact
    {
        public int PracticeContactId { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public int AddressId { get; set; }
        public string PracticeOther { get; set; }
        public string BillingContact { get; set; }
        public string BillingContactPhone { get; set; }
        public string ManagerName { get; set; }
        public string ManagerEmail { get; set; }
        public string ManagerPhone { get; set; }
        public string BillingContactEmail { get; set; }
        public string officedayshrs { get; set; }
        public System.DateTime CreateOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> Primaryaddrss { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Practice Practice { get; set; }
    }
}
