//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.PracticeProviders = new HashSet<PracticeProvider>();
            this.PracticeProviderLocations = new HashSet<PracticeProviderLocation>();
        }
    
        public int ProviderId { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string NPI { get; set; }
        public int Degree { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> ProviderIdentifier { get; set; }
        public Nullable<System.Guid> PrimaryAddressIdentifier { get; set; }
        public System.DateTime CreateOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string ProviderEmail { get; set; }
    
        public virtual Degree Degree1 { get; set; }
        public virtual ICollection<PracticeProvider> PracticeProviders { get; set; }
        public virtual ICollection<PracticeProviderLocation> PracticeProviderLocations { get; set; }
    }
}
