//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep
    {
        public int RepId { get; set; }
        public string RepsId { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string RepGroupsId { get; set; }
        public Nullable<int> RepGroupId { get; set; }
        public Nullable<int> MangerId { get; set; }
        public int RepStatusId { get; set; }
        public Nullable<System.DateTime> SignonDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> EmployeeStatusId { get; set; }
    }
}
