//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int RId { get; set; }
        public string ReportTypeId { get; set; }
        public Nullable<int> RepId { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string RepName { get; set; }
        public string RepGroupName { get; set; }
        public string PracticeName { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> InsurancePlanId { get; set; }
        public Nullable<int> InsuarancePlanTypeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
