//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class RxcReport
    {
        public int ScriptId { get; set; }
        public string DateReceived { get; set; }
        public string Rxno { get; set; }
        public string ScriptType { get; set; }
        public string ScriptNumber { get; set; }
        public string Formulations { get; set; }
        public string Status { get; set; }
        public string DateFilled { get; set; }
        public string RxcPlan { get; set; }
        public string InsPaid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string NpiNumber { get; set; }
    }
}
