//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class RxCScript
    {
        public int ScriptId { get; set; }
        public string DateReceived { get; set; }
        public Nullable<int> ScriptType { get; set; }
        public string ScriptNumber { get; set; }
        public string Formulations { get; set; }
        public Nullable<int> Staus { get; set; }
        public string DateFilled { get; set; }
        public Nullable<int> RxPlan { get; set; }
        public Nullable<int> Payement { get; set; }
        public string Notes { get; set; }
        public Nullable<int> RepId { get; set; }
        public string RepName { get; set; }
        public string RepGroupName { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> InsurencePlanId { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> InsurancePlanTypeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> EditedBy { get; set; }
    }
}
