//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusType
    {
        public StatusType()
        {
            this.Roles = new HashSet<Role>();
            this.tblGroups = new HashSet<tblGroup>();
        }
    
        public int StatusId { get; set; }
        public string StatusType1 { get; set; }
        public Nullable<System.DateTime> Creatd_On { get; set; }
        public Nullable<int> Creatd_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<int> Modified_By { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
        public virtual StatusType StatusTypes1 { get; set; }
        public virtual StatusType StatusType2 { get; set; }
        public virtual ICollection<tblGroup> tblGroups { get; set; }
    }
}
