//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        public int Address_Id { get; set; }
        public Nullable<int> Address_Type_Id { get; set; }
        public string Line_1 { get; set; }
        public string Line_2 { get; set; }
        public string City { get; set; }
        public Nullable<int> State_Id { get; set; }
        public string Zip { get; set; }
        public string Office_Hours { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_on { get; set; }
        public Nullable<int> Modified_By { get; set; }
    }
}
