//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toxicology
    {
        public int ScriptId { get; set; }
        public string RepGroup { get; set; }
        public string SpecimenID { get; set; }
        public string CollectedDt { get; set; }
        public string ReceivedDt { get; set; }
        public string Reported { get; set; }
        public string Clinician { get; set; }
        public string RepId { get; set; }
        public string RepName { get; set; }
        public string PracticeName { get; set; }
        public string ProviderName { get; set; }
        public string InsurancePlan { get; set; }
        public string InsuarancePlanType { get; set; }
        public string Status { get; set; }
        public string NpiNumber { get; set; }
        public string PayerName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
