//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.DataMigration.Database.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string Middle_Initial { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public Nullable<int> Dept { get; set; }
        public string Email { get; set; }
        public string Work_Email { get; set; }
        public string Home_Phone { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<int> Address_Id { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public byte[] newPassword { get; set; }
        public Nullable<bool> InspaidAccess { get; set; }
    }
}
