//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public Lead()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int Id { get; set; }
        public int PracticeId { get; set; }
        public Nullable<int> LeadSourceId { get; set; }
        public Nullable<int> RepId { get; set; }
        public string LeadServiceIntrest { get; set; }
        public bool IsActive { get; set; }
        public int LeadStatus { get; set; }
        public Nullable<bool> HasFlag { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string OtherLeadSource { get; set; }
        public Nullable<bool> IsConverted { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> OldId { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual LookupLeadSource LookupLeadSource { get; set; }
        public virtual Rep Rep { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual BusinessMaster BusinessMaster { get; set; }
    }
}
