//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupMarketingCategory
    {
        public LookupMarketingCategory()
        {
            this.MarketingDocuments = new HashSet<MarketingDocument>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> BusinessId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<MarketingDocument> MarketingDocuments { get; set; }
        public virtual BusinessMaster BusinessMaster { get; set; }
    }
}
