//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupNotificationType
    {
        public LookupNotificationType()
        {
            this.UserNotificationMappers = new HashSet<UserNotificationMapper>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string NotificationKey { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<UserNotificationMapper> UserNotificationMappers { get; set; }
    }
}
