//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMaster
    {
        public ReportMaster()
        {
            this.ReportColumnValues = new HashSet<ReportColumnValue>();
            this.ReportFinances = new HashSet<ReportFinance>();
            this.SalesImportDetails = new HashSet<SalesImportDetail>();
        }
    
        public int Id { get; set; }
        public int BusinessId { get; set; }
        public int ServiceId { get; set; }
        public int PatientId { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public Nullable<System.DateTime> SpecimenCollectionDate { get; set; }
        public Nullable<System.DateTime> SpecimenReceivedDate { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public string PracticeName { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string ProviderFirstName { get; set; }
        public string ProviderLastName { get; set; }
        public string ProviderNpi { get; set; }
        public Nullable<int> RepId { get; set; }
        public string RepFirstName { get; set; }
        public string RepLastName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsColumnValuesImported { get; set; }
        public string SpecimenId { get; set; }
        public Nullable<int> OldId { get; set; }
        public Nullable<int> OldReportId { get; set; }
    
        public virtual LookupEnrolledService LookupEnrolledService { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Rep Rep { get; set; }
        public virtual ICollection<ReportColumnValue> ReportColumnValues { get; set; }
        public virtual ICollection<ReportFinance> ReportFinances { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<SalesImportDetail> SalesImportDetails { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual BusinessMaster BusinessMaster { get; set; }
    }
}
