//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesImportSummery
    {
        public SalesImportSummery()
        {
            this.SalesImportDetails = new HashSet<SalesImportDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> ImportedDate { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public Nullable<int> RowsAffected { get; set; }
        public Nullable<int> NumberOfInserts { get; set; }
        public Nullable<int> NumberOfUpdates { get; set; }
        public Nullable<int> NumberOfSkips { get; set; }
        public Nullable<int> NumberOfFails { get; set; }
        public string ImportedFilePath { get; set; }
        public string LogFilePath { get; set; }
        public Nullable<int> DataMode { get; set; }
        public string MessageSummery { get; set; }
        public string IncomingFileName { get; set; }
    
        public virtual LookupEnrolledService LookupEnrolledService { get; set; }
        public virtual ICollection<SalesImportDetail> SalesImportDetails { get; set; }
        public virtual User User { get; set; }
        public virtual BusinessMaster BusinessMaster { get; set; }
    }
}
