//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesImportMessage
    {
        public int Id { get; set; }
        public int ImportDetailId { get; set; }
        public string ColumnName { get; set; }
        public string NodeName { get; set; }
        public string IncomingValue { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsFinance { get; set; }
        public Nullable<bool> IsTechnical { get; set; }
    
        public virtual SalesImportDetail SalesImportDetail { get; set; }
    }
}
