//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesImportDetail
    {
        public SalesImportDetail()
        {
            this.SalesImportMessages = new HashSet<SalesImportMessage>();
        }
    
        public int Id { get; set; }
        public int ImportSummeryId { get; set; }
        public string ImportedData { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> ImportStatus { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ReportMaster ReportMaster { get; set; }
        public virtual SalesImportSummery SalesImportSummery { get; set; }
        public virtual ICollection<SalesImportMessage> SalesImportMessages { get; set; }
    }
}
