//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBP.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserColumnVisibility
    {
        public int Id { get; set; }
        public int BusinessId { get; set; }
        public int UserId { get; set; }
        public int ModuleId { get; set; }
        public string ColumnName { get; set; }
        public string DisplayName { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual LookupEnrolledService LookupEnrolledService { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual BusinessMaster BusinessMaster { get; set; }
    }
}
